<a href="https://colab.research.google.com/github/adam404/jupyter-notebooks-public/blob/main/Numbpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numbpy Basics

I am trying to teach myself the basics I need to do machine learning for stock analysys and hopefully automated trading

https://numpy.org/doc/stable/user/quickstart.html



# Initialization

Initialize array to an incremented set 

In [ ]:
import numpy as np
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Creation from an array

In [18]:
>>> import numpy as np
>>> a = np.array([2,3,4])
>>> a

array([2, 3, 4])

# Reshaping

Change data into rows (3), columns (5)

In [ ]:
import numpy as np
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# Inspection

Get number of dimensions

In [13]:
import numpy as np
a = np.arange(15)
a.ndim

1


Get number of elements

In [11]:
import numpy as np
a = np.arange(15)
a.size

15


Get shape

In [15]:
import numpy as np
a = np.arange(15).reshape(3,5)
a.shape

(3, 5)

Get type

In [16]:
import numpy as np
a = np.arange(15).reshape(3,5)
a.dtype

dtype('int64')